# Generated by Django 3.1 on 2020-08-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast', models.BooleanField()),
                ('text', models.CharField(max_length=140)),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
